

version: '3'
services:
  web:
    build: ./
    image: ""
    restart: always
    environment:
      - JAR_FILE=/worker/app.jar
    ports:
      - "8096:8096"
    container_name: sxmd_springboot_generator

  mysql:
    image: "mysql"
    ports:
      - "3306:3306"
