
# Tomcat
server:
  port: 8096
  servlet:
    context-path: /

# 环境
spring:
  # 环境的选择   dev | prod
  profiles:
    active: dev
  # freemarker 配置
  freemarker:
    cache: false
    suffix: .html
    settings:
      template_update_delay: 0
      classic_compatible: true

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sxmd
  configuration:
    map-underscore-to-camel-case: true


# generator 配置
# 支持 postgresql /mysql/

sxmd:
  basedate: mysql


